### PR TITLE
Adding github profile

### PR DESCRIPTION
**Pull request by jcbatwork**
## Steps for creating Commit and Pull Request:

1. Forked main repository on github page.
2. Cloned remote repository into local with the next command:
```sh
$ git clone git@github.com:jcbatwork/week-1.git
```
3. Created the folder and _md_ file using Discord user profile name.
4. Added changes to the Stage area using the command:
```sh
$ git add "github-profiles/Jose C. Barahona-1862/Jose C. Barahona-1862.md"
```
5. Created a commit using the command:
```sh
$ git commit -m "add: added profile file"
```
6. Synchronized local repository with remote using the command:
```sh
$ git pull origin main
``` 
7. Added the changes to the remote repository:
```sh
$ git push -u origin main
```
8. Opened a pull request on github page.

### CODE REVIEW

**Review by Jorem999 — APPROVED** [review]
Perfecto!, se nota la experiencia 😃

**Comment by jcbatwork** [comment]
> Perfecto!, se nota la experiencia 😃

Gracias!

**Review by byRokii — APPROVED** [review]
Todo en orden amigo👌.

**Review by Yanina-Unrein — APPROVED** [review]
Esta perfecto!

**Comment by jcbatwork** [comment]
Gracias por sus reviews y sus comentarios.

Saludos!

**Pull request merged**
